services:
  redis:
    image: redis:alpine
    container_name: districhat_redis
    ports:
      - "6379:6379"
    networks:
      - districhat_network

  postgres:
    image: postgres:16-alpine
    container_name: districhat_postgres
    restart: always
    environment:
      POSTGRES_MULTIPLE_DATABASES: districhat_auth,districhat_chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - districhat_network

  auth-service:
    image: serversideup/php:8.4-cli
    container_name: districhat_auth
    volumes:
      - ./auth-service:/var/www/html:z
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - redis
      - postgres
    networks:
      - districhat_network

  chat-service:
    image: serversideup/php:8.4-cli
    container_name: districhat_chat_api
    volumes:
      - ./chat-service:/var/www/html:z
    ports:
      - "8001:8001"
    command: php artisan serve --host=0.0.0.0 --port=8001
    depends_on:
      - redis
      - auth-service
      - postgres
    networks:
      - districhat_network

  chat-websocket:
    image: serversideup/php:8.4-cli
    container_name: districhat_chat_ws
    volumes:
      - ./chat-service:/var/www/html:z
    ports:
      - "8080:8080"
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    depends_on:
      - redis
    networks:
      - districhat_network

  frontend:
    image: serversideup/php:8.4-cli
    container_name: districhat_frontend
    volumes:
      - ./frontend:/var/www/html:z
    ports:
      - "8002:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - auth-service
    networks:
      - districhat_network

networks:
  districhat_network:
    driver: bridge

volumes:
  postgres_data: